version: 2.1
jobs:
  build_synapse:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            IMAGE_NAME=raidennetwork/raiden-services-bundle \
            DOCKER_TAG=${CIRCLE_TAG:-nightly}-synapse; \
            docker build -t ${IMAGE_NAME}:${DOCKER_TAG} build/synapse ; \
            echo "$DEVOPS_DOCKERHUB_TOKEN" | docker login -u brainbotdevops --password-stdin ; \
            docker push ${IMAGE_NAME}:${DOCKER_TAG}
  build_db:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            IMAGE_NAME=raidennetwork/raiden-services-bundle \
            DOCKER_TAG=${CIRCLE_TAG:-nightly}-db; \
            docker build -t ${IMAGE_NAME}:${DOCKER_TAG} build/db ; \
            echo "$DEVOPS_DOCKERHUB_TOKEN" | docker login -u brainbotdevops --password-stdin ; \
            docker push ${IMAGE_NAME}:${DOCKER_TAG}
  build_well_known:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            IMAGE_NAME=raidennetwork/raiden-services-bundle \
            DOCKER_TAG=${CIRCLE_TAG:-nightly}-well_known_server; \
            docker build -t ${IMAGE_NAME}:${DOCKER_TAG} build/well_known_server ; \
            echo "$DEVOPS_DOCKERHUB_TOKEN" | docker login -u brainbotdevops --password-stdin ; \
            docker push ${IMAGE_NAME}:${DOCKER_TAG}

workflows:
  version: 2
  build_images:
    jobs:
      - build_synapse
      - build_db
      - build_well_known
